name: CI/CD

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!startsWith(github.ref, 'refs/tags/')"
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Linux
        run: |
          mkdir -p export/linux
          godot --headless --export-release "Linux" export/linux/DevourAll.x86_64

      - name: Export Windows
        run: |
          mkdir -p export/windows
          godot --headless --export-release "Windows Desktop" export/windows/DevourAll.exe

      - name: Export macOS
        run: |
          mkdir -p export/mac
          godot --headless --export-release "macOS" export/mac/DevourAll.zip

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: builds
          path: export/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Export Linux
        run: |
          mkdir -p export/linux
          godot --headless --export-release "Linux" export/linux/DevourAll.x86_64

      - name: Export Windows
        run: |
          mkdir -p export/windows
          godot --headless --export-release "Windows Desktop" export/windows/DevourAll.exe

      - name: Export macOS
        run: |
          mkdir -p export/mac
          godot --headless --export-release "macOS" export/mac/DevourAll.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            export/linux/DevourAll.x86_64
            export/windows/DevourAll.exe
            export/mac/DevourAll.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}